on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Server
        run: |
          sshpass -p "Eequalit9chaatho" ssh -o StrictHostKeyChecking=no abdulaziz@158.220.111.34 "
          cd Examify-FRONT &&
          git pull origin main &&
          docker build --rm -t examifyfront . &&
          # Check if the container exists and remove if it does
          if [ \$(docker ps -aq -f name=examifyfront) ]; then
            docker rm -f examifyfront
          fi
          # Stop any process using port 3020 to prevent conflicts
          if lsof -i:3020 -t; then
            kill -9 \$(lsof -i:3020 -t)
          fi
          # Run the new container
          docker run -d -p 3020:3000 --name examifyfront examifyfront
          "
